// Creates the ./config/config.ts file from environment variables.
// This is run as part of the build process.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const outDir = path.join(__dirname, "..", "config");
const outFile = path.join(outDir, "config.ts");

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir);
}

const content = `
// This file is auto-generated by scripts/buildConfig.js
// Do not edit this file directly.

export const STRIPE_DONATION_LINK = "${process.env.STRIPE_DONATION_LINK}";
export const PROD_DOMAIN = "${process.env.PROD_DOMAIN}";

`;

fs.writeFileSync(outFile, content.trim());

export {};
